In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier


dataset=pd.read_excel("/content/filee.xlsx")
dataset.head()

weight(x)  height(y)        class
0         51        167  underweight
1         62        182       normal
2         69        176       normal
3         64        173       normal
4         65        172       normal

In [ ]:
dataset=pd.read_excel("/content/filee.xlsx")
print(dataset.columns)
x=dataset[["weight(x)","height(y)"]].values
y=dataset["class"].values
print(x)
print(y)

Index(['weight(x)', 'height(y)', 'class'], dtype='object')
[[ 51 167]
 [ 62 182]
 [ 69 176]
 [ 64 173]
 [ 65 172]
 [ 56 174]
 [ 58 169]
 [ 57 173]
 [ 55 170]]
['underweight' 'normal' 'normal' 'normal' 'normal' 'underweight' 'normal'
 'normal' 'normal']


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[ 62 182]
 [ 65 172]
 [ 55 170]
 [ 58 169]
 [ 64 173]
 [ 51 167]
 [ 56 174]]
[[ 57 173]
 [ 69 176]]
['normal' 'normal' 'normal' 'normal' 'normal' 'underweight' 'underweight']
['normal' 'normal']


In [ ]:

knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
dataset=np.array([[57,170]])
y_pred=knn.predict(dataset)
print(y_pred)


['normal']
